# Generated by Django 3.0.4 on 2020-03-12 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200311_0709'),
        ('collaborate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborate',
            name='looking_for',
            field=models.ManyToManyField(related_name='skills_needed', to='accounts.Skill'),
        ),
    ]
