# Generated by Django 3.0.4 on 2020-05-11 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaborate', '0002_collaborate_looking_for'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collaborate',
            old_name='media',
            new_name='assets',
        ),
    ]
