# Generated by Django 3.0.4 on 2020-05-11 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0002_auto_20200311_2028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='showcase',
            old_name='content',
            new_name='assets',
        ),
    ]
