# Generated by Django 3.0.4 on 2020-06-15 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0005_media'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='media',
            new_name='media_files',
        ),
    ]
